### ISSUE TITLE
Fix the search bar in chat

### ISSUE THREAD

**Issue by frances-uy** [tryRebooting2023/askus#31]

**Comment by frances-uy** [comment]
Please do work for this task in a branch called "issue-031".

Search bar should automatically scroll to the bottom of the page, just like the chat boxes and sources do.

**Comment by jligeral** [comment]
I created a new component called 'NewSearchBar'  since I wanted to reduce repetitive code within 'Search.'  The general idea was to render the component after the very last response item, but within the loading spinner logic so that it showed up with the responses. I also set some conditions to disable the initial search bar meanwhile retaining its initial content.
